Libm cve 2020 10029
ForAllSecure/VulnerabilitiesLab pull request #17
Opened 2020-07-16 23:28 UTC by guidovranken

2020-07-21 20:46 UTC, sciencemanx requested changes
Great job on this! 2 things:
- Do we need the corpus to get the bug discovery in a reasonable amount of time? What is the time without it?
- When we get a final link for the blog post, lets put a link to it in both the main readme and the project specific one.

Thanks again!

2020-07-21 20:46 UTC, sciencemanx commented on README.md
> + * [GNU libm CVE-2020-10029](https://github.com/ForAllSecure/VulnerabilitiesLab/tree/master/libm-cve-2020-10029)
Let's move this to chronological order.

2020-07-21 20:46 UTC, sciencemanx commented on libm-cve-2020-10029/Dockerfile
> +RUN /build/build.sh
If possible, could we use a builder container to reduce the final container size?

2020-07-21 20:46 UTC, sciencemanx commented on libm-cve-2020-10029/README.md
> +and watch Mayhem replicate the bugs! These bugs take very little time (several seconds)
Is this true w/ or w/o corpus?

2020-07-21 20:46 UTC, sciencemanx commented on libm-cve-2020-10029/README.md
> +You should now be able to compile `libm-cve-2020-10029/src/libm-tester.c` against your library.
Nice! this is very cool

2020-07-21 20:46 UTC, sciencemanx commented on libm-cve-2020-10029/README.md
> +
We should include a comment about responsible disclosure in the intro section as well.

2020-07-22 00:36 UTC, guidovranken commented on libm-cve-2020-10029/README.md
> +
I put the disclosure timeline in the Timeline section right below. Or do you mean something else?

2020-07-22 00:43 UTC, guidovranken commented on libm-cve-2020-10029/Dockerfile
> +RUN /build/build.sh
How do you suggest we do that?

2020-07-22 00:55 UTC, guidovranken commented on libm-cve-2020-10029/README.md
> +and watch Mayhem replicate the bugs! These bugs take very little time (several seconds)
No. Actually I believe the corpus includes the crashing input. Without a corpus it takes at least longer than 10 minutes (I just confirmed that) and possibly hours. Maybe we should strike a balance by including only a random portion of the current corpus (that doesn't include the crasher), so that discovery will occur within a few minutes.

2020-07-22 14:58 UTC, sciencemanx commented on libm-cve-2020-10029/README.md
> +and watch Mayhem replicate the bugs! These bugs take very little time (several seconds)
I think that's a good idea. Definitely want speed but already having the bug might be too much speed haha 😅

2020-07-22 15:01 UTC, sciencemanx commented on libm-cve-2020-10029/Dockerfile
> +RUN /build/build.sh
After the top FROM you can specify "as builder" then you can do another FROM debian and COPY --from=builder to copy over the binary.

https://docs.docker.com/develop/develop-images/multistage-build/

2020-07-22 15:06 UTC, sciencemanx commented on libm-cve-2020-10029/README.md
> +
Yep. I think it might be a good idea to explicitly call it out for someone quickly scanning it or someone less familiar with the process. Alternatively, we could rename Timeline to Responsible Disclosure Timeline.

2020-07-29 23:10 UTC, guidovranken commented on libm-cve-2020-10029/Dockerfile
> +RUN /build/build.sh
Done.

2020-07-29 23:10 UTC, guidovranken commented on libm-cve-2020-10029/README.md
> +and watch Mayhem replicate the bugs! These bugs take very little time (several seconds)
I've reduced the corpus size to about 30 inputs. The crashing input is now not in the corpus. Mayhem finds it in about 30 seconds.

2020-07-29 23:11 UTC, guidovranken commented on libm-cve-2020-10029/README.md
> +
Done.

2020-08-04 16:52 UTC, sciencemanx reviewed
Thanks for the changes Guido! Everything here looks good. Just waiting for the blog post to be finalized to get this in.

2020-08-10 17:21 UTC, sciencemanx commented
Merging this to a branch on upstream (ForAllSecure/VulnerabilitiesLab) to get CI working properly

2020-08-10 17:21 UTC, merged