Add jq-defect-2020-1
ForAllSecure/VulnerabilitiesLab pull request #18
Opened 2020-07-21 18:24 UTC by mark-griffin

Adding Harrison's libprotobuf-mutator based reproducer of the JQ use-after-free.

2020-08-06 20:20 UTC, sciencemanx requested changes
Looks good. Just a couple comments on the mayhemfile and readme. Let me know what you think about the naming thing.

Only other thing is to add a link from the main readme to this one in the style of the ones already there.

Once the blog link is finalized, we can add it to both the main readme and this one.

2020-08-06 20:20 UTC, sciencemanx commented on .github/workflows/docker_publish.yml
> +          - jq-defect-2020-1
Since this doesn't have a CVE lets make it a date or just keep it a 2020 (instead of 2020-1) b/c it could be confusing

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/README.md
> +library for parsing and manipulating JSON.
Let's include information about the bug/possible "damage", mention responsible disclosure (and how its now fixed), and give credit to harrison with a link to his twitter or something.

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/README.md
> +The `poc/` directory contains a seed which triggers a heap use-after-free as
seed -> test case

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/README.md
> +detected by ASAN. This bug was reported to the maintainers of jq on 14 Feb
Lets mention Harrison here too ("...reported by Harrison, a ForAllSecure intern, to the..." etc)

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +    asan: true
depreciate manual cmd notation.

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +version: '1.2'
bump version to make sure the below works

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +duration: 600
I would double the time it took to find on staging etc. to make sure it is found in one run

2020-08-06 20:20 UTC, sciencemanx commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +target: fuzzer_jq_pair
lets match the name of the target to the directory name

2020-08-06 20:21 UTC, sciencemanx commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +version: '1.2'
I guess its above 🤷‍♂️

2020-08-11 17:07 UTC, mark-griffin commented on .github/workflows/docker_publish.yml
> +          - jq-defect-2020-1
I agree it looks cleaner without the "1", just going off what David had initially said. Changing throughout

2020-08-11 17:07 UTC, mark-griffin commented on jq-defect-2020-1/README.md
> +library for parsing and manipulating JSON.
Adding

2020-08-11 17:07 UTC, mark-griffin commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +version: '1.2'
Updating to 1.5

2020-08-11 17:07 UTC, mark-griffin commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +target: fuzzer_jq_pair
doing so.

2020-08-11 17:07 UTC, mark-griffin commented on jq-defect-2020-1/mayhem/jq_parse_fuzzer/Mayhemfile
> +duration: 600
done.

2020-08-21 17:25 UTC, merged